# GitLab CI/CD Configuration for oberon-lang
# Michael Grossniklaus, 2024

stages:
  - build
  - test
#  - deploy

compile:
  stage: build
  tags:
    - linux
  image: gitlab.inf.uni-konstanz.de:5050/michael.grossniklaus/oberon-lang:latest
  script:
    - echo "Compiling the code..."
    - mkdir build && cd build
    - cmake .. -G "Unix Makefiles"
    - make
  artifacts:
    name: 'oberon-lang'
    paths:
      - build/src/oberon-lang
      - build/liboberon/static/liboberon.*
      - build/liboberon/liboberon.*
      - build/liboberon/*.smb
    expire_in: 1 hour

test:
  stage: test
  tags:
    - linux
  needs:
    - compile
  image: gitlab.inf.uni-konstanz.de:5050/michael.grossniklaus/oberon-lang:latest
  script:
    - echo "Running unit tests..."
    - cd build
    - cmake .. -G "Unix Makefiles"
    - make test

#deploy:
#  stage: deploy
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
