name: Linux CI Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch :

env:
    build_type: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:    
      matrix:
        cc: [gcc, clang]
    
    steps:
    - uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt-get update &&
        sudo apt-get install libboost-all-dev libboost-filesystem-dev python3-pip

    - name: Install Clang 17
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh 17 all

    - name: Install lit & filecheck
      run: |
        sudo pip3 install lit
        sudo pip3 install filecheck

    - name: Configure CMake
      run: |
        if ["$MATRIX_CC" == "gcc"]
        then
        cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DLLVM_ROOT=/usr/lib/llvm-17 -DBoost_NO_BOOST_CMAKE=ON
        else
        cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DLLVM_ROOT=/usr/lib/llvm-17 -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_CXX_COMPILER=clang++-17 -DCMAKE_C_COMPILER=clang-17
        fi
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.build_type }}

    - name: Install
      run: cmake --install ${{ github.workspace }}/build --prefix install

    - name: Test
      run: cd ${{ github.workspace }}/build && make test >test_report_linux_${{ matrix.cc }}.txt || true

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: binary-linux-${{ matrix.cc }}-release
        path: ${{ github.workspace }}/install/**/*

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: test_report_linux_${{ matrix.cc }}.txt
        path: ${{ github.workspace }}/build/test_report_linux_${{ matrix.cc }}.txt

