name: Linux CI Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
    build_type: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name:
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install packages
      run: |
        sudo apt-get update &&
        sudo apt-get install libboost-program-options-dev libboost-filesystem-dev python3-pip

    - name: Install Clang 17
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh 17

    - name: Install lit & filecheck
      run: |
        sudo pip3 install lit
        sudo pip3 install filecheck

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ env.build_type }}

    - name: Install
      run: cmake --install ${{ steps.strings.outputs.build-output-dir }} --prefix install  || true

    - name: Test
      run: cd ${{ steps.strings.outputs.build-output-dir }} && make test || true

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binary-ubuntu-latest-release
        path: ${{ steps.strings.outputs.build-output-dir }}/install/**

