name: MacOS CI Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
    build_type: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Homebrew/actions/setup-homebrew@v2

    - name:
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install packages
      run: |
        brew install git &&
        brew install make &&
        brew install cmake &&
        brew install llvm@17 &&
        brew install boost &&
        brew install python

    - name: Install lit & filecheck
      run: |
        pip install lit &&
        pip install filecheck

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }} -G "Unix Makefiles"

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ env.build_type }}

    - name: Install
      run: cmake --install ${{ steps.strings.outputs.build-output-dir }} --prefix install  || true

    - name: Test
      run: cd ${{ steps.strings.outputs.build-output-dir }} && make test || true

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binary-macos-release
        path: ${{ steps.strings.outputs.build-output-dir }}/install/**

