name: MSVC (x64)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  build_type: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install package dependencies
      run: |
        vcpkg install boost-algorithm:x64-windows
        vcpkg install boost-convert:x64-windows
        vcpkg install boost-filesystem:x64-windows
        vcpkg install boost-program-options:x64-windows
        vcpkg install llvm[target-x86]:x64-windows

    - name: Install Python dependencies
      run: |
        pip3 install lit
        pip3 install filecheck
        pip3 install sphinx
        pip3 install sphinx_rtd_theme

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}\build -S ${{ github.workspace }} -G "Visual Studio 17 2022"
