name: MSYS2 CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
    build_type: Release

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        update: true

    - name: Install package dependencies
      run: |
        pacman --noconfirm -S git
        pacman --noconfirm -S make
        pacman --noconfirm -S mingw-w64-clang-x86_64-python-pip
        pacman --noconfirm -S mingw-w64-clang-x86_64-toolchain
        pacman --noconfirm -S mingw-w64-clang-x86_64-boost
        pacman --noconfirm -S mingw-w64-clang-x86_64-cmake

    - name: Install Python dependencies
      run: |
        pip3 install lit
        pip3 install filecheck
        pip3 install sphinx
        pip3 install sphinx_rtd_theme

    - name: Configure CMake
      run: >
        cmake -B "$GITHUB_WORKSPACE"/build
        -S "$GITHUB_WORKSPACE" -G "MSYS Makefiles"

    - name: Build compiler
      run: cmake --build "$GITHUB_WORKSPACE"/build --config ${{ env.build_type }}

    - name: Build documentation
      run: cmake --build "$GITHUB_WORKSPACE"/build --target docs

    - name: Install compiler
      run: cmake --install "$GITHUB_WORKSPACE"/build --prefix install

    - name: Run unit tests
      run: cmake --build "$GITHUB_WORKSPACE"/build --target test  | tee "$GITHUB_WORKSPACE"/build/test_report_msys2.txt

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: binary-msys2-release
        path: ${{ github.workspace }}/install/**/*

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: test_report_msys2.txt
        path: ${{ github.workspace }}/build/test_report_msys2.txt